### ISSUE TITLE
"There is a newer version of the PowerMTA plugin available." when using 0.0.4

### ISSUE THREAD

**Issue by svmaris** [jalalahmad/newrelic_pmta_agent#1]
I've installed the latest version of the plugin (0.0.4), but the New Relic web interface shows "There is a newer version of the PowerMTA plugin available." when I'm looking at the reports.

**Comment by jalalahmad** [comment]
Looking into it.

**Comment by ambled** [comment]
+1 on the 'newer version' alert.

**Comment by tjspinks** [comment]
also seeing the same issue when installing just today
