### ISSUE TITLE
/status information not found in PowerMTA

### ISSUE THREAD

**Issue by svmaris** [jalalahmad/newrelic_pmta_agent#2]
I'm using v0.0.4 of the plugin and I noticed the script does not find any metrics on http://pmtahost/status?format=xml. We're running Power MTA 4.0r9-201211271658.

I noticed that the webserver (pmtahttp) is responding with the wrong content-type for the status URL, so that might throw of the XML-parsing. This does not happen with the other request (domains and queues):

```
# curl -I "http://<host>/status?format=xml"
HTTP/1.1 200 Ok
Content-Type: text/html
Cache-Control: no-cache
Connection: close
```

**Comment by ambled** [comment]
I submitted a pull request https://github.com/jahmad-fareportal/newrelic_pmta_agent/pull/3 with a temporary(?) patch to get the statistics to work. If you have active support from Port25, please add a comment to the new "PowerMTA Support" forum thread I started: "status url returning incorrect Content-Type"

**Comment by svmaris** [comment]
Thanks @ambled, this patch seems to have fixed the status-metrics.

The plugin is still pretty broken for me though. The columns "Incoming messages" and "Outgoing messages" are showing values in milliseconds ("ms") which I doubt is correct. The detail pages for all my pmta hosts are empty. I see data being collected from newrelic_pmta_agent.rb, so I think this has something to do with the configuration on newrelic.com's side.

**Comment by svmaris** [comment]
Ignore the "detail pages for all my pmta hosts are empty"-part of my comment above. They magically started working again.

**Comment by ambled** [comment]
I can't see/edit the Dashboard without forking the project as my own plug-in, however "ms" may be a truncated from 'msgs' (or just poorly defined), as the metric itself aligns with the messages/min rate that I see from my web portal.

Note: PowerMTA 4.r15 that was just released contains this same xml bug.

**Comment by Power-MTA** [comment]
latest version powermta / pmta available with lifetime license key.
+ another tools available
Skype: salimrezabd04
Telegram: salimrezabd
Telegram: salimrezabd1
